/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconCarbonArrowRight: typeof import('~icons/carbon/arrow-right')['default']
    IconCarbonBook: typeof import('~icons/carbon/book')['default']
    IconCarbonChevronRight: typeof import('~icons/carbon/chevron-right')['default']
    IconCarbonClose: typeof import('~icons/carbon/close')['default']
    IconCarbonDocument: typeof import('~icons/carbon/document')['default']
    IconCarbonFaceDizzy: typeof import('~icons/carbon/face-dizzy')['default']
    IconCarbonFolder: typeof import('~icons/carbon/folder')['default']
    IconCarbonFolderOpen: typeof import('~icons/carbon/folder-open')['default']
    IconCarbonLanguage: typeof import('~icons/carbon/language')['default']
    IconCarbonMenu: typeof import('~icons/carbon/menu')['default']
    IconCarbonMoon: typeof import('~icons/carbon/moon')['default']
    IconCarbonPinFilled: typeof import('~icons/carbon/pin-filled')['default']
    IconCarbonRecentlyViewed: typeof import('~icons/carbon/recently-viewed')['default']
    IconCarbonSearch: typeof import('~icons/carbon/search')['default']
    IconCarbonSun: typeof import('~icons/carbon/sun')['default']
    IconCarbonTime: typeof import('~icons/carbon/time')['default']
    MarqueeNotice: typeof import('./components/ui/MarqueeNotice.vue')['default']
    NavTree: typeof import('./components/NavTree.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchModal: typeof import('./components/ui/SearchModal.vue')['default']
    ThemeToggle: typeof import('./components/ui/ThemeToggle.vue')['default']
  }
}
